"""
Export Service - Generate JSON, PDF, and QR exports
"""

import io
import json
from typing import List, Dict, Any
from datetime import datetime
import base64
import hashlib


class ExportService:
    """Handles export functionality for analysis results."""
    
    def generate_qr_data_url(self, data: str, session_id: str) -> str:
        """Generate a data URL for QR code (simplified)."""
        # In production, use qrcode library to generate actual QR
        # This is a placeholder that returns a placeholder URL
        placeholder = f"https://api.qrserver.com/v1/create-qr-code/?size=200x200&data={data}"
        return placeholder
    
    def generate_party_ledger_report(self, party_ledger: List[Dict], transactions: List[Dict], session_id: str) -> bytes:
        """Generate a PDF report of party ledger (simplified text format)."""
        # In production, use reportlab for proper PDF
        report_lines = [
            "=" * 60,
            "ACUTRACE - PARTY LEDGER REPORT",
            "=" * 60,
            f"Session ID: {session_id}",
            f"Generated: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}",
            "=" * 60,
            "",
            "PARTY LEDGER SUMMARY",
            "-" * 60,
        ]
        
        for party in party_ledger:
            report_lines.append(f"Party: {party['party']}")
            report_lines.append(f"  Transactions: {party['total_transactions']}")
            report_lines.append(f"  Total Credit: ₹{party['total_credit']:,.2f}")
            report_lines.append(f"  Total Debit: ₹{party['total_debit']:,.2f}")
            report_lines.append(f"  Net Amount: ₹{party['net_amount']:,.2f}")
            report_lines.append(f"  Entity Type: {party['entity_type']}")
            report_lines.append("")
        
        report_lines.extend([
            "-" * 60,
            f"Total Parties: {len(party_ledger)}",
            f"Total Transactions: {len(transactions)}",
            "=" * 60,
            "Generated by AcuTrace - Party Ledger & Fund Flow Intelligence"
        ])
        
        report_text = "\n".join(report_lines)
        return report_text.encode('utf-8')
    
    def generate_json_export(self, data: Dict[str, Any]) -> str:
        """Generate JSON export string."""
        return json.dumps(data, indent=2, default=str)
    
    def generate_fund_flow_report(self, chains: List[Dict], session_id: str) -> bytes:
        """Generate a text report of fund flow chains."""
        report_lines = [
            "=" * 60,
            "ACUTRACE - FUND FLOW CHAIN REPORT",
            "=" * 60,
            f"Session ID: {session_id}",
            f"Generated: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}",
            f"Total Chains: {len(chains)}",
            "=" * 60,
            "",
        ]
        
        for i, chain in enumerate(chains, 1):
            report_lines.extend([
                f"Chain {i}:",
                f"  Flow Path: {chain.get('flow_path', 'N/A')}",
                f"  Total Amount: ₹{chain.get('total_amount', 0):,.2f}",
                f"  Confidence: {chain.get('confidence', 0):.2%}",
                f"  Transactions: {chain.get('transaction_count', 0)}",
                ""
            ])
        
        report_lines.extend([
            "=" * 60,
            "Generated by AcuTrace - Party Ledger & Fund Flow Intelligence"
        ])
        
        report_text = "\n".join(report_lines)
        return report_text.encode('utf-8')

